import type { IntegrationCategory, IntegrationKind } from "./index";

// Canonical catalog entries. Persisted into public.integration_catalog by
// migrations 0020 + 0023; mirrored here so the UI can render before the DB
// row loads and so future provider implementations can branch on entry.slug
// without round-tripping.
//
// SCOPE NOTE: only brands whose logo is in the bundled icon registry land
// here. Saudi-specific providers (Moyasar, Tap, PayTabs, STC Pay, Unifonic,
// Veo, Wyscout, Spond, TeamSnap) and brands missing from simple-icons v13
// upstream (Microsoft Teams/Outlook/OneDrive, Hudl, Klaviyo, ActiveCampaign,
// Amplitude, Freshdesk) are temporarily removed from the catalog UI. Re-add
// once we hand-curate their SVG paths into the registry.

export interface CatalogEntry {
  slug: string;
  name_ar: string;
  name_en: string;
  category: IntegrationCategory;
  short_description_ar: string;
  short_description_en: string;
  kinds: ReadonlyArray<IntegrationKind>;
  availability: "available" | "coming_soon";
  simple_icon: string | null;
  brand_color: string;
}

export const CATALOG: ReadonlyArray<CatalogEntry> = [
  // ─── Communications (6) ─────────────────────────────────────
  {
    slug: "slack",
    name_ar: "سلاك",
    name_en: "Slack",
    category: "communications",
    short_description_ar: "أرسل إشعارات النادي إلى قنوات الفريق على Slack.",
    short_description_en: "Pipe club notifications into Slack channels for the staff team.",
    kinds: ["send_message"],
    availability: "coming_soon",
    simple_icon: "slack",
    brand_color: "611F69",
  },
  {
    slug: "whatsapp-railway",
    name_ar: "واتساب (Railway)",
    name_en: "WhatsApp (Railway)",
    category: "communications",
    short_description_ar: "رموز التحقق وتنبيهات الأعضاء عبر حساب واتساب شخصي.",
    short_description_en: "Deliver OTPs and member alerts via a self-hosted WhatsApp client.",
    kinds: ["send_message"],
    availability: "coming_soon",
    simple_icon: "whatsapp",
    brand_color: "25D366",
  },
  {
    slug: "whatsapp-meta",
    name_ar: "WhatsApp Business (Meta Cloud)",
    name_en: "WhatsApp Business (Meta Cloud)",
    category: "communications",
    short_description_ar: "واجهة Meta Cloud API الرسمية للأندية الكبرى.",
    short_description_en: "Meta's official Cloud API for higher throughput.",
    kinds: ["send_message"],
    availability: "coming_soon",
    simple_icon: "whatsapp",
    brand_color: "1877F2",
  },
  {
    slug: "discord",
    name_ar: "ديسكورد",
    name_en: "Discord",
    category: "communications",
    short_description_ar: "قنوات مشجعين ومجتمعات الأكاديميات على Discord.",
    short_description_en: "Fan channels and academy community servers on Discord.",
    kinds: ["send_message"],
    availability: "coming_soon",
    simple_icon: "discord",
    brand_color: "5865F2",
  },
  {
    slug: "telegram",
    name_ar: "تيليجرام",
    name_en: "Telegram",
    category: "communications",
    short_description_ar: "بث الإشعارات إلى قنوات Telegram العامة للأعضاء.",
    short_description_en: "Broadcast notifications to public Telegram channels for members.",
    kinds: ["send_message"],
    availability: "coming_soon",
    simple_icon: "telegram",
    brand_color: "26A5E4",
  },
  {
    slug: "twilio",
    name_ar: "تويليو",
    name_en: "Twilio",
    category: "communications",
    short_description_ar: "رسائل SMS واتصالات صوتية للأعضاء حول العالم.",
    short_description_en: "International SMS + voice calls for member notifications.",
    kinds: ["send_message"],
    availability: "coming_soon",
    simple_icon: "twilio",
    brand_color: "F22F46",
  },

  // ─── Productivity (8) ───────────────────────────────────────
  {
    slug: "google-calendar",
    name_ar: "تقويم Google",
    name_en: "Google Calendar",
    category: "productivity",
    short_description_ar: "مزامنة المباريات والحصص التدريبية مع تقويم النادي.",
    short_description_en: "Sync fixtures and academy sessions to your team calendar.",
    kinds: ["sync_calendar"],
    availability: "coming_soon",
    simple_icon: "googlecalendar",
    brand_color: "4285F4",
  },
  {
    slug: "notion",
    name_ar: "Notion",
    name_en: "Notion",
    category: "productivity",
    short_description_ar: "ادفع تقارير الحوكمة والاجتماعات إلى مساحة Notion.",
    short_description_en: "Push governance reports + meeting minutes into Notion.",
    kinds: ["sync_contacts"],
    availability: "coming_soon",
    simple_icon: "notion",
    brand_color: "000000",
  },
  {
    slug: "google-drive",
    name_ar: "Google Drive",
    name_en: "Google Drive",
    category: "productivity",
    short_description_ar: "أرشف الوثائق المالية ومستندات الحوكمة في Drive.",
    short_description_en: "Archive finance + governance documents to Drive.",
    kinds: ["sync_contacts"],
    availability: "coming_soon",
    simple_icon: "googledrive",
    brand_color: "1FA463",
  },
  {
    slug: "dropbox",
    name_ar: "Dropbox",
    name_en: "Dropbox",
    category: "productivity",
    short_description_ar: "تخزين سحابي بديل وأرشفة المرفقات الإدارية.",
    short_description_en: "Cloud storage alternative + admin attachment archive.",
    kinds: ["sync_contacts"],
    availability: "coming_soon",
    simple_icon: "dropbox",
    brand_color: "0061FF",
  },
  {
    slug: "asana",
    name_ar: "Asana",
    name_en: "Asana",
    category: "productivity",
    short_description_ar: "تتبّع المشاريع التشغيلية للنادي في Asana.",
    short_description_en: "Track club operational projects in Asana.",
    kinds: ["sync_contacts"],
    availability: "coming_soon",
    simple_icon: "asana",
    brand_color: "F06A6A",
  },
  {
    slug: "trello",
    name_ar: "Trello",
    name_en: "Trello",
    category: "productivity",
    short_description_ar: "لوحات Kanban للحوكمة والمسؤولية المجتمعية.",
    short_description_en: "Kanban boards for governance + CSR initiatives.",
    kinds: ["sync_contacts"],
    availability: "coming_soon",
    simple_icon: "trello",
    brand_color: "0079BF",
  },
  {
    slug: "airtable",
    name_ar: "Airtable",
    name_en: "Airtable",
    category: "productivity",
    short_description_ar: "قواعد بيانات قابلة للتعاون لإدارة الفعاليات.",
    short_description_en: "Collaborative databases for managing events + rosters.",
    kinds: ["sync_contacts"],
    availability: "coming_soon",
    simple_icon: "airtable",
    brand_color: "18BFFF",
  },
  {
    slug: "zoom",
    name_ar: "Zoom",
    name_en: "Zoom",
    category: "productivity",
    short_description_ar: "جدول اجتماعات مجلس الإدارة عبر Zoom من سبورلو.",
    short_description_en: "Schedule board + staff meetings directly from Sporlo.",
    kinds: ["sync_calendar"],
    availability: "coming_soon",
    simple_icon: "zoom",
    brand_color: "0B5CFF",
  },

  // ─── Marketing (5) ──────────────────────────────────────────
  {
    slug: "mailchimp",
    name_ar: "Mailchimp",
    name_en: "Mailchimp",
    category: "marketing",
    short_description_ar: "زامن قاعدة الأعضاء وأطلق حملات من سبورلو.",
    short_description_en: "Sync members as audience + launch campaigns from Sporlo.",
    kinds: ["sync_contacts", "send_email"],
    availability: "coming_soon",
    simple_icon: "mailchimp",
    brand_color: "FFE01B",
  },
  {
    slug: "resend",
    name_ar: "Resend",
    name_en: "Resend",
    category: "marketing",
    short_description_ar: "بريد transactional لرسائل بوابة الأعضاء والدعوات.",
    short_description_en: "Transactional email for portal links and teammate invites.",
    kinds: ["send_email"],
    availability: "available",
    simple_icon: "resend",
    brand_color: "000000",
  },
  {
    slug: "sendgrid",
    name_ar: "SendGrid",
    name_en: "SendGrid",
    category: "marketing",
    short_description_ar: "بديل بريد transactional للفرق المؤسسية.",
    short_description_en: "Enterprise-style transactional email alternative.",
    kinds: ["send_email"],
    availability: "coming_soon",
    simple_icon: "sendgrid",
    brand_color: "1A82E2",
  },
  {
    slug: "brevo",
    name_ar: "Brevo",
    name_en: "Brevo",
    category: "marketing",
    short_description_ar: "بريد وتسويق عبر SMS من مزوّد أوروبي.",
    short_description_en: "Email + SMS marketing from a European-based provider.",
    kinds: ["send_email", "send_message"],
    availability: "coming_soon",
    simple_icon: "brevo",
    brand_color: "0B996E",
  },
  {
    slug: "hubspot",
    name_ar: "HubSpot",
    name_en: "HubSpot",
    category: "marketing",
    short_description_ar: "أتمتة تسويق متقدمة وعلاقات عملاء راعين النادي.",
    short_description_en: "Advanced marketing automation + sponsor CRM.",
    kinds: ["sync_contacts", "send_email"],
    availability: "coming_soon",
    simple_icon: "hubspot",
    brand_color: "FF7A59",
  },

  // ─── Analytics (4) ──────────────────────────────────────────
  {
    slug: "google-analytics",
    name_ar: "Google Analytics",
    name_en: "Google Analytics",
    category: "analytics",
    short_description_ar: "تتبّع زيارات الموقع العام للنادي وبوابة الأعضاء.",
    short_description_en: "Track public club site + member portal page views.",
    kinds: ["track_event"],
    availability: "coming_soon",
    simple_icon: "googleanalytics",
    brand_color: "E37400",
  },
  {
    slug: "mixpanel",
    name_ar: "Mixpanel",
    name_en: "Mixpanel",
    category: "analytics",
    short_description_ar: "أرسل أحداث سبورلو الرئيسية إلى Mixpanel.",
    short_description_en: "Pipe key Sporlo events into Mixpanel.",
    kinds: ["track_event"],
    availability: "coming_soon",
    simple_icon: "mixpanel",
    brand_color: "7856FF",
  },
  {
    slug: "hotjar",
    name_ar: "Hotjar",
    name_en: "Hotjar",
    category: "analytics",
    short_description_ar: "خرائط حرارة وتسجيل جلسات لتحسين تجربة المشجع.",
    short_description_en: "Heatmaps + session recordings for fan UX research.",
    kinds: ["track_event"],
    availability: "coming_soon",
    simple_icon: "hotjar",
    brand_color: "FD3A5C",
  },
  {
    slug: "plausible",
    name_ar: "Plausible",
    name_en: "Plausible Analytics",
    category: "analytics",
    short_description_ar: "تحليلات خفيفة محترمة للخصوصية بدون كوكيز.",
    short_description_en: "Lightweight privacy-friendly analytics, cookie-free.",
    kinds: ["track_event"],
    availability: "coming_soon",
    simple_icon: "plausibleanalytics",
    brand_color: "5850EC",
  },

  // ─── Payments (2) ───────────────────────────────────────────
  {
    slug: "stripe",
    name_ar: "Stripe",
    name_en: "Stripe",
    category: "payments",
    short_description_ar: "بوابة دفع عالمية لاستقبال مدفوعات الرعاية الخارجية.",
    short_description_en: "Global payment gateway for international sponsorship.",
    kinds: ["receive_payment"],
    availability: "coming_soon",
    simple_icon: "stripe",
    brand_color: "635BFF",
  },
  {
    slug: "apple-pay",
    name_ar: "Apple Pay",
    name_en: "Apple Pay",
    category: "payments",
    short_description_ar: "خيار الدفع الافتراضي لمستخدمي أجهزة Apple.",
    short_description_en: "Default checkout option for Apple device owners.",
    kinds: ["receive_payment"],
    availability: "coming_soon",
    simple_icon: "applepay",
    brand_color: "000000",
  },

  // ─── Social (6) ─────────────────────────────────────────────
  {
    slug: "meta-business",
    name_ar: "Meta للأعمال",
    name_en: "Meta Business (FB + IG)",
    category: "social",
    short_description_ar: "انشر آلياً على Facebook و Instagram من سبورلو.",
    short_description_en: "Auto-publish to Facebook + Instagram from Sporlo.",
    kinds: ["social_post"],
    availability: "coming_soon",
    simple_icon: "meta",
    brand_color: "0467DF",
  },
  {
    slug: "x-twitter",
    name_ar: "X (تويتر سابقاً)",
    name_en: "X (formerly Twitter)",
    category: "social",
    short_description_ar: "نشر مباشر للأخبار وآخر النتائج على منصة X.",
    short_description_en: "Direct posting for news + live scores on X.",
    kinds: ["social_post"],
    availability: "coming_soon",
    simple_icon: "x",
    brand_color: "000000",
  },
  {
    slug: "tiktok",
    name_ar: "TikTok",
    name_en: "TikTok",
    category: "social",
    short_description_ar: "محتوى قصير من خلف الكواليس وأهداف المباريات.",
    short_description_en: "Short-form content: behind-the-scenes + match goals.",
    kinds: ["social_post"],
    availability: "coming_soon",
    simple_icon: "tiktok",
    brand_color: "010101",
  },
  {
    slug: "youtube",
    name_ar: "YouTube",
    name_en: "YouTube",
    category: "social",
    short_description_ar: "بث مباشر للمباريات والمحتوى الطويل.",
    short_description_en: "Live match streams + long-form content.",
    kinds: ["social_post"],
    availability: "coming_soon",
    simple_icon: "youtube",
    brand_color: "FF0000",
  },
  {
    slug: "linkedin",
    name_ar: "LinkedIn",
    name_en: "LinkedIn",
    category: "social",
    short_description_ar: "إعلانات الشراكات والوظائف الإدارية للنادي.",
    short_description_en: "Sponsorship announcements + club executive hiring.",
    kinds: ["social_post"],
    availability: "coming_soon",
    simple_icon: "linkedin",
    brand_color: "0A66C2",
  },
  {
    slug: "buffer",
    name_ar: "Buffer",
    name_en: "Buffer",
    category: "social",
    short_description_ar: "جدولة منشورات السوشيال من لوحة واحدة.",
    short_description_en: "Schedule social posts from a single dashboard.",
    kinds: ["social_post"],
    availability: "coming_soon",
    simple_icon: "buffer",
    brand_color: "168EEA",
  },

  // ─── Support (2) ────────────────────────────────────────────
  {
    slug: "zendesk",
    name_ar: "Zendesk",
    name_en: "Zendesk",
    category: "support",
    short_description_ar: "نظام تذاكر دعم محترف لطلبات الأعضاء.",
    short_description_en: "Pro-grade ticketing system for member inquiries.",
    kinds: ["customer_support"],
    availability: "coming_soon",
    simple_icon: "zendesk",
    brand_color: "03363D",
  },
  {
    slug: "intercom",
    name_ar: "Intercom",
    name_en: "Intercom",
    category: "support",
    short_description_ar: "دردشة مباشرة للموقع العام مع بوت AI.",
    short_description_en: "Live chat for the public site, with AI assist.",
    kinds: ["customer_support"],
    availability: "coming_soon",
    simple_icon: "intercom",
    brand_color: "1F8DED",
  },

  // ─── Automation (2) ─────────────────────────────────────────
  {
    slug: "zapier",
    name_ar: "Zapier",
    name_en: "Zapier",
    category: "automation",
    short_description_ar: "اربط سبورلو بأكثر من 6000 تطبيق دون كود.",
    short_description_en: "Connect Sporlo to 6000+ apps with no code.",
    kinds: ["automate"],
    availability: "coming_soon",
    simple_icon: "zapier",
    brand_color: "FF4F00",
  },
  {
    slug: "make",
    name_ar: "Make",
    name_en: "Make (Integromat)",
    category: "automation",
    short_description_ar: "أتمتة بصرية متقدمة لتدفقات العمل المعقدة.",
    short_description_en: "Visual automation for complex workflows.",
    kinds: ["automate"],
    availability: "coming_soon",
    simple_icon: "make",
    brand_color: "6D00CC",
  },
];

export const CATEGORY_ORDER: ReadonlyArray<IntegrationCategory> = [
  "communications",
  "productivity",
  "marketing",
  "analytics",
  "payments",
  "social",
  "support",
  "automation",
];
